---
  - name: clone tcloud repo
    git: repo={{ git_repo }} dest={{ dir_destination }}

  - name: install node modules
    npm: path: {{ dir_destination }}/{{ git_repo_name }} state=latest

  - name: start tcloud server
    command: npm start {{ dir_destination }}/{{ git_repo_name }}
