---
  - name: clone tcloud repo
    git: repo={{ git_repo }} dest={{ dir_destination }}

  - name: install node modules
    npm: path={{ dir_destination }} state=latest
    notify:
      - start tcloud
